# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import spes.spes.federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadChunk = channel.stream_unary(
                '/FederatedServer/UploadChunk',
                request_serializer=federated__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=federated__pb2.UploadChunkResponse.FromString,
                _registered_method=True)
        self.DownloadChunk = channel.unary_unary(
                '/FederatedServer/DownloadChunk',
                request_serializer=federated__pb2.DownloadChunkRequest.SerializeToString,
                response_deserializer=federated__pb2.DownloadChunkResponse.FromString,
                _registered_method=True)


class FederatedServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadChunk(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadChunk(self, request, context):
        """你原有的UploadWeights/DownloadWeights可保留兼容小模型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadChunk,
                    request_deserializer=federated__pb2.UploadChunkRequest.FromString,
                    response_serializer=federated__pb2.UploadChunkResponse.SerializeToString,
            ),
            'DownloadChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadChunk,
                    request_deserializer=federated__pb2.DownloadChunkRequest.FromString,
                    response_serializer=federated__pb2.DownloadChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederatedServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FederatedServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/FederatedServer/UploadChunk',
            federated__pb2.UploadChunkRequest.SerializeToString,
            federated__pb2.UploadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederatedServer/DownloadChunk',
            federated__pb2.DownloadChunkRequest.SerializeToString,
            federated__pb2.DownloadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
