# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\"o\n\x12UploadChunkRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x10\n\x08\x63hunk_id\x18\x03 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x04 \x01(\x05\x12\x12\n\nchunk_data\x18\x05 \x01(\x0c\"&\n\x13UploadChunkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"G\n\x14\x44ownloadChunkRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x10\n\x08\x63hunk_id\x18\x03 \x01(\x05\"N\n\x15\x44ownloadChunkResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x12\n\nlast_chunk\x18\x02 \x01(\x08\x12\r\n\x05ready\x18\x03 \x01(\x08\x32\x8d\x01\n\x0f\x46\x65\x64\x65ratedServer\x12:\n\x0bUploadChunk\x12\x13.UploadChunkRequest\x1a\x14.UploadChunkResponse(\x01\x12>\n\rDownloadChunk\x12\x15.DownloadChunkRequest\x1a\x16.DownloadChunkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADCHUNKREQUEST']._serialized_start=19
  _globals['_UPLOADCHUNKREQUEST']._serialized_end=130
  _globals['_UPLOADCHUNKRESPONSE']._serialized_start=132
  _globals['_UPLOADCHUNKRESPONSE']._serialized_end=170
  _globals['_DOWNLOADCHUNKREQUEST']._serialized_start=172
  _globals['_DOWNLOADCHUNKREQUEST']._serialized_end=243
  _globals['_DOWNLOADCHUNKRESPONSE']._serialized_start=245
  _globals['_DOWNLOADCHUNKRESPONSE']._serialized_end=323
  _globals['_FEDERATEDSERVER']._serialized_start=326
  _globals['_FEDERATEDSERVER']._serialized_end=467
# @@protoc_insertion_point(module_scope)
